# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/natan/UnrealEngine-5.3
GAMEPROJECTFILE =/home/natan/Downloads/Campus_Itabira/Campus_Itabira.uproject

TARGETS = \
	Campus_Itabira-Linux-Debug  \
	Campus_Itabira-Linux-DebugGame  \
	Campus_Itabira-Linux-Test  \
	Campus_Itabira-Linux-Shipping  \
	Campus_Itabira \
	Campus_ItabiraEditor-Linux-Debug  \
	Campus_ItabiraEditor-Linux-DebugGame  \
	Campus_ItabiraEditor-Linux-Test  \
	Campus_ItabiraEditor-Linux-Shipping  \
	Campus_ItabiraEditor \
	UnrealClient-Linux-Debug  \
	UnrealClient-Linux-DebugGame  \
	UnrealClient-Linux-Test  \
	UnrealClient-Linux-Shipping  \
	UnrealClient \
	UnrealEditor-Linux-Debug  \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Test  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-Debug  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Test  \
	UnrealGame-Linux-Shipping  \
	UnrealGame \
	UnrealServer-Linux-Debug  \
	UnrealServer-Linux-DebugGame  \
	UnrealServer-Linux-Test  \
	UnrealServer-Linux-Shipping  \
	UnrealServer\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend Campus_ItabiraEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug Campus_ItabiraEditor-Linux-Debug


Campus_Itabira-Linux-Debug:
	 $(PROJECTBUILD) Campus_Itabira Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

Campus_Itabira-Linux-DebugGame:
	 $(PROJECTBUILD) Campus_Itabira Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

Campus_Itabira-Linux-Test:
	 $(PROJECTBUILD) Campus_Itabira Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

Campus_Itabira-Linux-Shipping:
	 $(PROJECTBUILD) Campus_Itabira Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

Campus_Itabira:
	 $(PROJECTBUILD) Campus_Itabira Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

Campus_ItabiraEditor-Linux-Debug:
	 $(PROJECTBUILD) Campus_ItabiraEditor Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

Campus_ItabiraEditor-Linux-DebugGame:
	 $(PROJECTBUILD) Campus_ItabiraEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

Campus_ItabiraEditor-Linux-Test:
	 $(PROJECTBUILD) Campus_ItabiraEditor Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

Campus_ItabiraEditor-Linux-Shipping:
	 $(PROJECTBUILD) Campus_ItabiraEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

Campus_ItabiraEditor:
	 $(PROJECTBUILD) Campus_ItabiraEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealClient-Linux-Debug:
	 $(BUILD) UnrealClient Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealClient-Linux-DebugGame:
	 $(BUILD) UnrealClient Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealClient-Linux-Test:
	 $(BUILD) UnrealClient Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealClient-Linux-Shipping:
	 $(BUILD) UnrealClient Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealClient:
	 $(BUILD) UnrealClient Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Debug:
	 $(BUILD) UnrealEditor Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Test:
	 $(BUILD) UnrealEditor Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Debug:
	 $(BUILD) UnrealGame Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Test:
	 $(BUILD) UnrealGame Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealServer-Linux-Debug:
	 $(BUILD) UnrealServer Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealServer-Linux-DebugGame:
	 $(BUILD) UnrealServer Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealServer-Linux-Test:
	 $(BUILD) UnrealServer Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealServer-Linux-Shipping:
	 $(BUILD) UnrealServer Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealServer:
	 $(BUILD) UnrealServer Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
